dist: trusty
language: python

python:
  - 3.4

before_install:
  - sudo apt-get install ruby-sass

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - coverage run --omit '*virtualenv/*' manage.py test

after_success:
  - coveralls

notifications:
  email: false
