language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install python-coveralls

script:
  - coverage run --omit 'env/*' manage.py test

after_success:
  - codecov
  - coveralls

notifications:
  email: false
