language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - coverage run --omit '*virtualenv/*' manage.py test

after_success:
  - coveralls

notifications:
  email: false
