# Generated by Django 2.1 on 2018-12-22 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import training.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndomondoWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endomondo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_started', models.DateTimeField(default=None, null=True)),
                ('time_finished', models.DateTimeField(default=None, null=True)),
                ('time_updated', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['-time_started'],
            },
        ),
        migrations.CreateModel(
            name='Gpx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', training.models.SportField(max_length=20)),
                ('distance', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GpxTrackPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('hr', models.PositiveSmallIntegerField(default=None, null=True)),
                ('cad', models.PositiveSmallIntegerField(default=None, null=True)),
                ('time', models.DateTimeField()),
                ('gpx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Gpx')),
            ],
        ),
        migrations.CreateModel(
            name='Reps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Excercise')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=None, null=True)),
                ('duration', models.DurationField(default=None, null=True)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Excercise')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default=None, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(default=None, max_length=200)),
                ('started', models.DateTimeField(default=None, null=True)),
                ('finished', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
        migrations.AddField(
            model_name='gpx',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Workout'),
        ),
        migrations.AddField(
            model_name='excercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Workout'),
        ),
        migrations.AddField(
            model_name='endomondoworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Workout'),
        ),
    ]
