# Generated by Django 2.1 on 2018-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
