# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_authkeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndomondoWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endomondo_id', models.IntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Workout')),
            ],
        ),
    ]
