# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_endomondoworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpx',
            name='length_3d',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
