# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_auto_20160827_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpx',
            name='length_2d',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
