# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20160827_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excercise',
            options={'ordering': ['time_started']},
        ),
    ]
