# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 13:23
from __future__ import unicode_literals

from django.db import migrations


def copy_workout_type(apps, schema_editor):
    Workout = apps.get_model("training", "Workout")
    for workout in Workout.objects.all():
        if workout.gpx_set.count() > 0:
            workout.workout_type = workout.gpx_set.get().activity_type
            workout.save()
        else:
            workout.workout_type = "strength"
            workout.save()


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_workout_workout_type'),
    ]

    operations = [
        migrations.RunPython(copy_workout_type)
    ]
