# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_auto_20160918_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpx',
            name='length_3d',
        ),
    ]
