# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 07:54
from __future__ import unicode_literals

from django.db import migrations
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_auto_20161001_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpx',
            name='activity_type',
            field=training.models.SportField(max_length=20),
        ),
    ]
