# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 07:56
from __future__ import unicode_literals

from django.db import migrations


def make_activity_type_lower(apps, schema_editor):
    Gpx = apps.get_model("training", "Gpx")
    for gpx in Gpx.objects.all():
        gpx.activity_type = gpx.activity_type.lower()
        gpx.save()


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_auto_20161004_0754'),
    ]

    operations = [
        migrations.RunPython(make_activity_type_lower)
    ]
