# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0031_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excercise',
            options={'ordering': ['-time_started']},
        ),
    ]
