# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0034_auto_20170312_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(default=None, null=True)),
                ('time_finished', models.DateTimeField(default=None, null=True)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Excercise')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
