# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0035_timers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
