# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_auto_20170528_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
