# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_auto_20170528_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timers',
            name='time_finished',
        ),
        migrations.AddField(
            model_name='timers',
            name='duration',
            field=models.DurationField(default=None, null=True),
        ),
    ]
